### ISSUE TITLE
Does the function ''earcut with hole'' expects 2d array of the points representing hole?

### ISSUE THREAD

**Issue by sebmooreaz** [nwiswakarma/EarcutPlugin#1]
Hello, I have a list of points that define a polygon shape (outer shape)

And I then have a hole in the shape (inner shape)

![earcutholes](https://user-images.githubusercontent.com/35493664/68018748-353f1300-fc9a-11e9-9e3a-1d2598249dd2.png)

Do I need to input all the 2d points of the hole in the In hole points input of the node?

Or do I have to do it like in the earcut doc=
''holes is an array of hole indices if any (e.g. [5, 8] for a 12-vertex input would mean one hole with vertices 5–7 and another with 8–11).'' 

Thanks

**Comment by nwiswakarma** [comment]
EarcutWithHole() is specifically used for polygon with only a single hole. The usage would be to specify outer points with "InPoints" and separate inner points with "InHolePoints".

If you want to have multiple polygon holes you may use EarcutPolygons() with point index ranges input or EarcutPolygonsByIndexOffset() with point index offsets. EarcutPolygonsByIndexOffset() is probably the more intuitive of the two.

Using your example, if there are 12 points 0-4 outer points, 5-7 first inner points, and 8-11 the second inner points, InPolyIndexOffsets input for EarcutPolygonsByIndexOffset() would be [5, 8].

**Comment by nwiswakarma** [comment]
This plugin, as with my other repositories, is intended for my personal use but I'm open to improve for the use case of anyone interested. I don't document my code explicitly but made sure that the code semantics are able to document itself.

If you are interested in any other repositories or functionality feel free to discuss. I mainly focus on procedural world building.

**Comment by sebmooreaz** [comment]
Hi Nwiswakarma,

Thank you for your replies, it really helps. I think it would greatly increase the reach of your work if you made a good documentation. Especially if people want to grasp how it works. Your plugins are really interesting. I did not have any problem with UE4.23. Thank you Nwiswakarma!

**Comment by nwiswakarma** [comment]
It must be noted that some of the plugins in my repositories have c++ specific third-party library. Therefore, if you intend to use the library on non c++ platform some porting work might be required. 

Although most of the plugins compiles with 4.23, the ones that use access to graphics pipeline, such as ProceduralMeshUtility, RenderingUtilityLibrary, etc. should not compile right away. Unreal Engine graphics pipeline have been updated every single engine version since around 4.17 with 4.23 being the most significant update yet. Therefore, I haven't got around to do compatibility update.

I put the repositories for public just in case anyone happen to come by. Most code commits also change the APIs significantly, explicit documentation would be obsolete really fast. I would probably document them after I finished my current project.

Since you are not experiencing any more problem I would also close this issue.
